### PR TITLE
added favourites search

### PR DESCRIPTION
**Pull request by david-morris**
Basic favourites search is implemented.
This should close issue #27 .

### CODE REVIEW

**Comment by david-morris** [comment]
I just realized I implemented this without integrating the Common Play Framework.  I should fix that before this can be merged.

**Comment by david-morris** [comment]
Ok, I've just integrated the hook into the common play framework.  This has also started the process of using regexes through adapt in line with #29 , and even though we need a helper to use them with the common play framework, it should be language independent so we can move towards solving #14 .

**Review by pcwii — CHANGES_REQUESTED** [review]
Is this speak command for diagnostic purposes? I would like to see this use a self.speak_dialog so that is language agnostic.
image

**Comment by david-morris** [comment]
Good point, I've added that as a dialog.  I should note, that warning gets skipped with the common play system code path, since I figure it's bad practice to give users information about searches that aren't fruitful when they're searching all skills.

**Pull request merged**
